### ISSUE TITLE
Use SDK on Huawei tablet

### ISSUE THREAD

**Issue by YanCorey** [pivo-inc/pivo-pro-sdk-testapp-android#1]
Device info:
Model number: HUAWEI M2-801W
EMUI version: EMUI 4.0.3
android version: 6.0

When I scan the device, the app will print PivoProSDK: NotFound.
Does the SDK not support tablets?

**Comment by nxt-kevin** [comment]
Hi @YanCorey ,
In general, we do not suggest using Pivo with tablet because of the weight, and the tablet may fall down. However, when the situation is suitable, tablets are supported.
Please make sure that you have a valid license file with your app, has BLE support, and GPS is enabled. If the device is still not discoverable, please try to use newer Tablet with higher Android version.

**Comment by YanCorey** [comment]
HI @nxt-kevin , 
Ok i try again
How can I listen to the callback without a device, or need to set a timeout in the app.

**Comment by nxt-kevin** [comment]
Could you deliberate more your situation? I don't think I get your question clearly

**Comment by YanCorey** [comment]
Hello 
I mean for the scanning device timeout, is it set in the SDK and give a callback, or it is recommended to customize when applying integration.

**Comment by ws707** [comment]
Hello @YanCorey.
Basically, there is no scanning timeout. However, there is a callback while scanning (Indefinite, until it is connected or cancelled). 
`
PivoEventBus.subscribe(
            PivoEventBus.SCAN_DEVICE, this, Consumer {
                 // Scanning here you can perform time out then call after you perferred timeout PivoProSdk.getInstance.stopScan()
                // if a device a is found 
               if (it is PivoEvent.Scanning){
                 list.add(it.device)
            }
        })
`
